Iter1
ujwegh/gophermart pull request #1
Opened 2023-12-13 20:08 UTC by ujwegh

2023-12-22 20:40 UTC, capsulated requested changes
В принципе, всё очень даже хорошо. 

Небольшие замечания оставил, можно в ответ писать, если вдруг с чем-то не согласен. 

А в общем, отлично организована структура приложения, по сервисам, нескольким репозиториям, легко читать код и ориентироваться в нём 👍

Так как время ещё есть, возвращаю на изменение по добавлен комментариям

2023-12-22 20:40 UTC, capsulated commented on cmd/gophermart/main.go
> +// @title           Swagger Docs for Gophermart API
Swagger документацию хорошо бы убрать из cmd к примеру в handlers. Эти теги необязательно в `cmd` добавлять?

2023-12-22 20:40 UTC, capsulated commented on cmd/gophermart/main.go
> +	go func() {
Обычно в самый конец `cmd` добавляется select с прослушиванием канала, и там весь gracefull shotdown, так как это завершение программы. А сервер можно в го-рутине запустить. Это по-желанию

2023-12-22 20:40 UTC, capsulated commented on cmd/gophermart/main.go
> +	// Server run context
От комментариев лучше избавляться, вместо них можно логи поставить: `log.println("Server context starts...")`

2023-12-22 20:40 UTC, capsulated commented on docs/docs.go
> +package docs
Скорее имя пакета swagger, тогда сразу ясно, что это

2023-12-22 20:40 UTC, capsulated commented on internal/app/handlers/balance_handler.go
> +// GetBalance godoc
Вот такие коменты - это хорошо. Если на основе их также сгенерить readme.md или какую-то wiki / documentation то вообще идеально

2023-12-22 20:40 UTC, capsulated commented on internal/app/handlers/balance_handler_easyjson.go
easyjson.go - круто 👍

2023-12-22 20:40 UTC, capsulated commented on internal/app/models/models.go
> +	User struct {
Все модели в одном пакете это удобно, но получается у всех других пакетов будет зависимость на импорт этого пакета. Это же структуры для базы данных? В один пакет всё лучше не складывать, а делить их по категориям, в соответсвии к которым относятся модели. Либо прям в пакете репозитория их переместить, если они не импортируются и используются только там.

Если gotpermart развивался, как настоящий проект, то этот пакет "разбух" бы от постоянно добавляющихся новых моделей

2023-12-22 20:40 UTC, capsulated commented on internal/app/repository/order_repository.go
> +	appErrors "github.com/ujwegh/gophermart/internal/app/errors"
С error'ами также, как и с моделями, лучше их определить либо там, где используются, либо разбить на разные категории (db, net и тп)

2023-12-22 20:40 UTC, capsulated commented on internal/app/repository/order_repository_test.go
> +CREATE TABLE IF NOT EXISTS orders
init.sql удобно добавлять. Они обычно сразу в контейнер подключаются, но в нашем случае можно их выполнить из файла

2023-12-22 20:40 UTC, capsulated commented on internal/app/router/router.go
> +func setupCORS() func(http.Handler) http.Handler {
А чего он тут в отрыве от своих из пакета middleware? ))))

2023-12-22 20:40 UTC, capsulated commented on internal/app/service/order_service.go
> +	} else if order != nil && userUID.String() == order.UserUUID.String() {
else не нужен, после return else никогда выполнится, а без него читать удобнее))

2023-12-22 20:40 UTC, capsulated commented on migrations/001_init_db.sql
> +-- +goose Up
О, а init скрипт-то есть) 👍  тогда строки CREATE TABLE только в тестах - вполне ок

2023-12-23 08:24 UTC, ujwegh commented on cmd/gophermart/main.go
> +// @title           Swagger Docs for Gophermart API
насколько я понял да, делал как в либе https://github.com/swaggo/http-swagger + когда генерирую доки нужно указывать именно директорию с main. ну и команда генерации первым параметром требует путь к main, а затем к моим хендлерам (swag init -d ./cmd/gophermart,./internal/app/handlers)

2023-12-23 08:29 UTC, ujwegh commented on docs/docs.go
> +package docs
так это сам сваггер сгенерил и вроде как он прямо просит DO NOT EDIT)

2023-12-23 09:05 UTC, ujwegh commented on internal/app/repository/order_repository.go
> +	appErrors "github.com/ujwegh/gophermart/internal/app/errors"
немного не понял про разделение на категории, вообще изначально думал определить енум с определенными кодами ошибок и пропихивать их при создании, но это будет не сильно отличаться от того что сейчас) В данном случае  appErrors "github.com/ujwegh/gophermart/internal/app/errors" это лишь обертка над любой ошибкой. Я использую ее для последующей сериализации в json с ошибкой на фронт. вот тут 
<img width="756" alt="image" src="https://github.com/ujwegh/gophermart/assets/30325542/790f9fb9-9745-44e0-bd18-b81665bc4a0d">

2023-12-23 10:03 UTC, ujwegh commented on internal/app/service/order_service.go
> +	} else if order != nil && userUID.String() == order.UserUUID.String() {
убрал

2023-12-23 10:03 UTC, ujwegh commented on internal/app/router/router.go
> +func setupCORS() func(http.Handler) http.Handler {
поправил

2023-12-23 10:05 UTC, ujwegh commented on internal/app/repository/order_repository_test.go
> +CREATE TABLE IF NOT EXISTS orders
тут отдельный скрипт вообще мне это очень сильно не нравится, на мой взгляд бд для тестов и реальная бд должна быть одна и та же. а тут у меня sqlite. Наиболее правильный вариант втащить testcontainers и поднимать постгрю рядом в контейнере. Но я решил сильно не заморачиваться над этим. наверное стоит сделать интеграционные тесты нормально

2023-12-23 10:05 UTC, ujwegh commented on internal/app/models/models.go
> +	User struct {
разнес

2023-12-23 10:12 UTC, ujwegh commented on cmd/gophermart/main.go
> +	// Server run context
вообще комменты добавлял специально чтоб разделить как то объявление) убрал

2023-12-23 10:12 UTC, ujwegh commented on cmd/gophermart/main.go
> +	go func() {
поправил

2023-12-27 13:46 UTC, capsulated commented on cmd/gophermart/main.go
> +// @title           Swagger Docs for Gophermart API
Да, есть там такое, что в main аннотации надо добавлять... Эх, не очень это красиво выглядит. Путь остаётся, зато swagger ui удобный. Вообще, я бы подумал, как его спрятать может отдельным cmd или app, но пока не ясно, как это лучше сделать

2023-12-27 13:48 UTC, capsulated commented on cmd/gophermart/main.go
> +	// Server run context
В целях обучения, в принципе ок, но в реальных production проектах лучше именовать и ставить логи так, чтобы комментарии не требовались. Бывают исключения, типа каких нибудь регулярок или совсем непонятных кусков кода, где просто не обойтись без комментария

2023-12-27 13:52 UTC, capsulated commented on docs/docs.go
> +package docs
А, это swagger прям создаёт папку docs? Тогда ок, оставляем. Конечно, не самый удобный пакет для сваггера, так как его использование немного валияет на структуру приложения, а это не очень хорошо. Лучше, когда всё гибко кастомизируется

2023-12-27 13:55 UTC, capsulated commented on internal/app/models/models.go
> +	User struct {
Часто слой entity - глобальный, чтобы все могли импортировать entity/models. Вот [тут](https://habr.com/ru/articles/718916/) можно почитать про подходы, но к сожалению для php, а не go 😬

2023-12-27 14:02 UTC, capsulated commented on internal/app/repository/order_repository.go
> +	appErrors "github.com/ujwegh/gophermart/internal/app/errors"
То есть, ошибки баз данных - это категория ошибок именно слоя баз данных. Ошибки http - это категория ошибок слоя хендлеров/роутера/http-сервера. Обычно так их категоризируют. И может быть ещё трейс вызовов: тоесть произошла ошибка в хендлере, к примеру, `не удалось записать данные заказа, с статусом 409` - это ошибка уровня хендлеров, а также ошибка уровня хранилки -  `невозможно выполнить INSERT - запись по этому заказу уже существует` - это ошибка слоя хранилки, которая и вернула и инициализировала ошибку в хендлере. Это для примера

2023-12-27 14:04 UTC, capsulated commented on internal/app/repository/order_repository_test.go
> +CREATE TABLE IF NOT EXISTS orders
В рамках данной работы - это совсем мелочи. В реальных проектах часто init.sql скрипты, а для тестов - отдельные dev и stage (идентичный боевому) контейнеры с базами для тестов. Строку с созданием таблицы можно и оставить в нашем случае

2023-12-27 14:09 UTC, capsulated approved these changes
В общем, всё супер

Круто, что использовал easy_json, swagger, хоть он и "засорил" код некоторыми комментариями (я бы подумал, как это обыграть). Код читаемый, понятный, структурированный. Отличная коммуникация по обсуждению ревью 👍

Комментарии оставил, но это уже больше в рамках обсуждения, а не ошибок

2024-01-05 17:02 UTC, merged